# Generated by Django 4.2.5 on 2023-11-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoredb',
            name='Language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookstoredb',
            name='Type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
